### PR TITLE
possible fix for broken !hash 

### PR DESCRIPTION
**Pull request by MSFTserver**
example code: https://jsfiddle.net/36rsry67/8/

### CODE REVIEW

**Comment by lyoshenka** [comment]
@filipnyquist is lord of the wunderbot. assigning this to him

**Comment by lyoshenka** [comment]
@MSFTserver this should be squashed down into one commit before merging

**Comment by MSFTserver** [comment]
@lyoshenka yea i decided to trim it down from my original i can submit a new PR if needed with 1 commit

**Comment by MSFTserver** [comment]
was a very sloppy way to parse the json

**Comment by MSFTserver** [comment]
Closing to Submit Cleaner PR

**Pull request closed without merging**
