### PR TITLE
Updates to rolesetter and default config

### PR DESCRIPTION
**Pull request by Coolguy3289**
I have added a parent if statement to check if someone runs the !addrole or !delrole command without a suffix. I have also confirmed a basic config to use as a template.

### CODE REVIEW

**Comment by tzarebczan** [comment]
@Coolguy3289 should I close this? What are the next steps?

**Comment by Coolguy3289** [comment]
This has been ready for a merge since I started this PR.

**Comment by tzarebczan** [comment]
Oh, thought there might be some older formatting (prettier) issues or something.

I know we spoke about not having a particular need for this at the moment, but doesn't hurt to get it in and explore some ideas. 

@filipnyquist please review / merge at your earliest convenience

**Comment by Coolguy3289** [comment]
On a previous PR I did some housekeeping around the bot. But this one was to purely fix the loop when no roles were mentioned.

**Pull request merged**
