### PR TITLE
update statbot.js

### PR DESCRIPTION
**Pull request by ykris45**
add IDR from cryptocompare and Australian Dollar , i Hope its can be merged.. i just helping out to make this bots more better

### CODE REVIEW

**Comment by ykris45** [comment]
Please add Eur if this PR merged. I saw this has been deleted

**Comment by MSFTserver** [comment]
your using an older version of pricebot.js you could remove that and keep stats.js

**Comment by tzarebczan** [comment]
Chris - please close this and delete your branch. Start your new changes on new branch.

**Comment by ykris45** [comment]
Okey. Sorry for late. Im busy right now

**Pull request closed without merging**
