### PR TITLE
re-added claim metadata

### PR DESCRIPTION
**Pull request by nikooo777**
This version will depend on the explorer API to retrieve the metadata.
I'd suggest running "npm install" before starting it again.

### CODE REVIEW

**Comment by nikooo777** [comment]
Here is a preview of the changes 

https://scrn.storni.info/2017-06-12_02-10-53-010948698.png

**Comment by lyoshenka** [comment]
In the future, please separate autoformatting and the actual changes into separate commits. Looking at this PR, its impossible to find what actually changed because there's tons of noise.

**Comment by lyoshenka** [comment]
This PR also makes the claimbot dependent on explorer. If explorer is down or unresponsive for some reason, claimbot also breaks (since it throws an error if the metadata request fails). Please fix it so that it still works if explorer request fails.

**Comment by lyoshenka** [comment]
Finally, are we sure this is necessary? The channel is already there in the URI, right above the name.

**Comment by nikooo777** [comment]
will do so, thanks for the feedback. I hadn't realized the auto formatting until i was ready to push the code, I'll avoid that next time.

Yes i'm aware it breaks if the explorer is unresponsive, a fallback solution would be to spin up another service on the server where wunderbot runs with the decoder (not an explorer instance). 

That could replace the dependency altogether but it requires an additional (small) service to be running as well.

(https://github.com/cryptodevorg/lbry-decoder), what do you think of this approach?

Also, what are you referring to with the last comment? If you're referring to "Channel: @....." then yeah, it can be removed, i thought that having it showing on its own would make it more visible

**Comment by nikooo777** [comment]
I also considered recoding the decoder in node to remove the dependencies completely, but i don't have the time for it now, so it's not a viable solution

**Comment by filipnyquist** [comment]
I would say it would be nice to have(as i right now have no idea of whats behind the links when looking in the channel), the dep of the explorer might be a problem(could just spin up a instance of that python script or create that decoder in nodejs

**Comment by lyoshenka** [comment]
I think an easier change would be to just return to the old behavior when the request to explorer fails. Don't choke and error out, just show the data we have and skip the rest.

**Comment by filipnyquist** [comment]
@lyoshenka that sounds like a great idea!

**Pull request merged**
