### PR TITLE
coinmarketcap V2

### PR DESCRIPTION
**Pull request by ykris45**
with add JSON Api code to newest version

### CODE REVIEW

**Comment by Coolguy3289** [comment]
Just reviewed the code, Not sure on how the API interacts, @ykris45 If you tested this on another Discord and it is resolving okay, then the this commit looks good. The Syntax LGTM

**Comment by ykris45** [comment]
@Coolguy3289 i doesnt have a server. or test on liberium discord server. Thanks for approved my PR

**Comment by Coolguy3289** [comment]
@ykris45 For future reference, I suggest you create your own discord, and get a version of the bot running there so that you can test your code before you make a PR, this way you know it works the way it should.

**Comment by ykris45** [comment]
okay @Coolguy3289 . if any question about setup my discord server. i will ask you on #discord 
but i doesnt have a server to test it. my comp is to old

**Comment by ykris45** [comment]
based on @MSFTserver review .

**Comment by tzarebczan** [comment]
@filipnyquist is this ready to be merged?

**Pull request merged**
