### PR TITLE
add fiat prices to hash bot[done]

### PR DESCRIPTION
**Pull request by MSFTserver**
this adds fiat prices to hash bot
image

### CODE REVIEW

**Comment by tzarebczan** [comment]
LGTM

**Comment by nikooo777** [comment]
I can't merge this one either, I need to find the time to review this code and submit my suggestion as there are a few things that aren't good enough (at least to my opinion).
I'm confident that I can give you a few heads up and get this merged afterwards

**Comment by MSFTserver** [comment]
ahh so me doing my cleaning out of repos messed with merging i thought that would be an issue i can open another one if needed but i think you can handle it if not just lmk

**Comment by filipnyquist** [comment]
@nikooo777 could you specify what could be done better so he can fix this and we can get it added. Thanks!

**Comment by nikooo777** [comment]
so. Github command line instructions messed me up a bit as I ended up refactoring what was there before this commit. I wonder why.

Anyway my changes are in https://github.com/lbryio/lbry-wunderbot/tree/hashbot-refactoring and should be the base for this PR.
There is a lot of code repetition that has to be avoided or otherwise nobody will be able to improve it in the future, also all VARs will have to disappear before I can merge it.

Let's see what I can port over in the next 30 minutes. (i'll push to that branch)

**Comment by nikooo777** [comment]
@MSFTserver please take a look at the above branch. I tried importing all your changes but i'm unsure if that's enough. I don't have any more time today to dedicate at this PR however you should checkout my branch and test it locally. If all the hash commands work then please either update this PR or resubmit a new one

**Comment by MSFTserver** [comment]
Will do

**Comment by MSFTserver** [comment]
opening new valid pr

**Pull request closed without merging**
