### PR TITLE
create altstats.js

### PR DESCRIPTION
**Pull request by MSFTserver**
image
like the new stats.js and btc/altprice bot, pulls any alt from CMC

### CODE REVIEW

**Comment by nikooo777** [comment]
does this command have a rate limit? I would make sure to add that before possibly rolling it out in order to prevent spam and DoS

**Comment by MSFTserver** [comment]
@nikooo777 this is what is says on CMC, Please limit requests to no more than 10 per minute.
Endpoints update every 5 minutes.

**Comment by filipnyquist** [comment]
As @nikooo777 said some sort of caching would be good, just a simple variable, i.e the example nikoo sent in discord :)

**Comment by MSFTserver** [comment]
@nikooo777 you want to do this cache since im not really sure how to yet but once you do it i can do in the future for other stuff that needs that i might make

**Comment by filipnyquist** [comment]
As said a cache will be needed before i´ll merge this PR, after that some improvements will be added to the content bot.

**Comment by tzarebczan** [comment]
@MSFTserver next steps here?

**Comment by MSFTserver** [comment]
@tzarebczan just need a cache function to cache varaible as coin name and save data for atleast like 5 minutes

**Pull request closed without merging**
