### PR TITLE
update statsbot.js

### PR DESCRIPTION
**Pull request by ykris45**
ADD IDR (Indonesian Rupiah)

### CODE REVIEW

**Comment by MSFTserver** [comment]
i think you need to learn a little about java a api/json calls and parsing

**Comment by MSFTserver** [comment]
i think i properly added this for you on my PR #21

**Comment by ykris45** [comment]
Thanks . i didnt know better about programing . and i will learn this . i just only know microcontroler . thanks for add IDR again in (21)

**Comment by lyoshenka** [comment]
can this be closed?

**Comment by filipnyquist** [comment]
Not needed as #21 has it included and are merged

**Pull request closed without merging**
