### PR TITLE
added some commands and bold -new

### PR DESCRIPTION
**Pull request by ykris45**
newly codes guys. based on new FAQ

### CODE REVIEW

**Comment by ykris45** [comment]
@tzarebczan can you review this sir. and suggest me to add new helpcommands if it would be added

**Comment by tzarebczan** [comment]
Looks good, removed the first part of the reply.

**Comment by ykris45** [comment]
approved..  LGTM Mr Thomas..

**Comment by filipnyquist** [comment]
Merged!

**Pull request merged**
