### PR TITLE
PICKLE RICK!!!

### PR DESCRIPTION
**Pull request by kennethreitz**
I realize he no longer carries cash, however, it's Pickle Rick — this is mandatory — at least for a short period of time. 

Signed-off-by: Kenneth Reitz <me@kennethreitz.org>

### CODE REVIEW

**Comment by tzarebczan** [comment]
Ha, why not right?

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kauffj** [comment]
Wow @lyoshenka I can't believe this hasn't been merged and deployed -- Pickle Rick obviously justifies an urgent rating on a PR.

**Comment by lyoshenka** [comment]
I changed the icon on slack and saved it as a new file in the repo

**Comment by kennethreitz** [comment]
✨🍰✨

**Pull request closed without merging**
