### PR TITLE
fix aliases

### PR DESCRIPTION
**Pull request by MSFTserver**
to use aliases youll need to create a alias.json in the folder with bot.js 
Example:
```
{
"tests":"stats"
}
```

### CODE REVIEW

**Comment by tzarebczan** [comment]
@MSFTserver what is this for exactly?

**Comment by MSFTserver** [comment]
it's just a fix for the alias.json that is in the bit we never had it working properly or tried to figure it out but it was broken and bow it's fixed

**Comment by MSFTserver** [comment]
basically set command aliases so says you want !stats to reply to something else too like !overview

**Comment by tzarebczan** [comment]
@filipnyquist can you review and see if this is still needed?

**Comment by filipnyquist** [comment]
The question is if we need aliases now or if it could wait for the next wunderbot release

**Comment by MSFTserver** [comment]
why leave broken code...

**Comment by tzarebczan** [comment]
What's next here?

**Comment by MSFTserver** [comment]
nothing it's basically done just needs to be merged

**Comment by tzarebczan** [comment]
@filipnyquist please merge or close based on your assessment. We aren't really using the feature yet, so up to you.

**Comment by Coolguy3289** [comment]
That last commit was me resolving the conflicts from the current master branch into this branch.

**Comment by tzarebczan** [comment]
@filipnyquist :) ?

**Comment by filipnyquist** [comment]
Driving home, will check soon.
// Sent from Android Auto

**Comment by filipnyquist** [comment]
Is this in a working stage, what is needed for it to be deployed?

**Comment by MSFTserver** [comment]
basically nothing it's ready just if you want to use it need to create a alias.json file in /bot like my first comment says

**Comment by filipnyquist** [comment]
This has now been merged and deployed in production! Hit me up if we need any aliases!

**Pull request merged**
