### PR TITLE
Some Updates

### PR DESCRIPTION
**Pull request by Coolguy3289**
Going through all of the code correcting Typos.

### CODE REVIEW

**Comment by Coolguy3289** [comment]
Pretty sure I have them all now.

**Comment by Coolguy3289** [comment]
I'm also going to write into this pull request to move the ping command to it's own module file, as well as make the Help command look nicer upon run.

**Comment by MSFTserver** [comment]
dont forget to delete the tip bot checks in bot.js if your deleting it

**Comment by MSFTserver** [comment]
https://github.com/lbryio/lbry-wunderbot/blob/faf6fa62744fe24a5a203be8ec3975a4bb1132e2/bot/bot.js#L47

**Comment by Coolguy3289** [comment]
Yup, On my list! :)

**Comment by filipnyquist** [comment]
Prettier has been added, this pull will be remade with the new git-precommit hook!

**Pull request closed without merging**
