### PR TITLE
Update claimbot.js

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by nikooo777** [comment]
why 4?

**Comment by ykris45** [comment]
@nikooo777 see discord guys. maybe should make 0.000 LBC (4) Before 0.00

**Comment by nikooo777** [comment]
Ok. please always provide a description or context in a pull request so that we know what's going on. we like to keep things on github so everyone understands what a PR is for and so on.
Merging (will let Filip deploy)

**Comment by ykris45** [comment]
@nikooo777 hehe sorry. im in a  not good condition bro

**Comment by tzarebczan** [comment]
@filipnyquist please revisit based on my comment. Bids can go down to 8 decimals.

**Pull request merged**
