### PR TITLE
[Complete] move icon link to spee.ch

### PR DESCRIPTION
**Pull request by ykris45**
i already download the pinky LBRY Heart from imgur and upload to spee.ch , so love all LBRY Product

### CODE REVIEW

**Comment by tzarebczan** [comment]
this LGTM, @filipnyquist please merge when you get a chance.

**Comment by ykris45** [comment]
@tzarebczan Thanks you for mention filip, i waited it 18 days ago..

**Comment by ykris45** [comment]
@nikooo777 thanks for merging my previous PR on tipbot area. please merge this PR, i waited long time ago..

**Comment by ykris45** [comment]
@nikooo777 thanks you so much nikoo.. 20 days wait this chance...  patienly is the key for success

**Comment by nikooo777** [comment]
unfortunately @filipnyquist is busy so we couldn't be faster.

I'm going to handle further requests so hopefully they're going to be much faster

**Pull request merged**
