### PR TITLE
split example file into two examples bot and function [done]

### PR DESCRIPTION
**Pull request by MSFTserver**

### CODE REVIEW

**Comment by filipnyquist** [comment]
What is the need of doing this? Wouldnt it be better to keep it in one file?

**Comment by MSFTserver** [comment]
yes its nice to keep it in one file but i feel alot are gonna be confused the difference between command and function

**Comment by MSFTserver** [comment]
i could also just leave it as one file and separate the more with some more helpful comments

**Comment by MSFTserver** [comment]
i just mind myself explaining to people if you making a command you dont need to use the initfunction/custom fields

**Comment by MSFTserver** [comment]
you choose which one you like better this or PR #64

**Pull request closed without merging**
