### PR TITLE
Fix lbryan role

### PR DESCRIPTION
**Pull request by littlemadhatter**
Editing out lbryan since it confuses people with lbryian

### CODE REVIEW

**Comment by Coolguy3289** [comment]
This role exists for the LBRYans united hive.

**Comment by littlemadhatter** [comment]
Oh, Then it should be named to LBRYans (United hive) to less confuse people then

**Comment by Coolguy3289** [comment]
That's up to @jring-o but I'm okay with the role being renamed to LBRYansUnited instead.

**Comment by littlemadhatter** [comment]
If he accepts that change, i'll start a PR or just let him do it, in any case i'm going to wait for his response before I close this

**Comment by littlemadhatter** [comment]
Ok, i'm going to make a new PR since I accidentally deleted the repository so I can't make new edits

**Pull request closed without merging**
