### PR TITLE
Add naming commands

### PR DESCRIPTION
**Pull request by ykris45**
My initiave

### CODE REVIEW

**Comment by tzarebczan** [comment]
Add it to the list of commands too please. Same branch.

**Comment by ykris45** [comment]
I think there also in commands V2 . Bundled with this sir.

**Comment by MSFTserver** [comment]
since this is open could you !bounty command to link to bounty page please and thanks :+1:

**Comment by ykris45** [comment]
I'm finished  MSFT . send from Lenovo Vibe K4 Note Using Chrome Mobile

**Comment by tzarebczan** [comment]
Thanks @ykris45 ! LGTM, I'll let @filipnyquist merge at his convenience.

**Comment by nikooo777** [comment]
Thank you. this looks good

**Comment by ykris45** [comment]
you welcome sir

**Pull request merged**
