### PR TITLE
add lbc to 1 lambo to pricebot! [done]

### PR DESCRIPTION
**Pull request by MSFTserver**
image

### CODE REVIEW

**Comment by tzarebczan** [comment]
for the lulz :)

**Comment by nikooo777** [comment]
Could you please remove the console logs from the code before i merge this?
bonus points if you also remove all the `var` and use `let` instead.
You'd have to adjust scoped of variables as described here: https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable

**Comment by MSFTserver** [comment]
i found mos thing i wouldnt need to define the lets or vars like ive been doing tested it on one with no lets or vars in the areas you didnt like them and it still worked not sure if this an option we can do

**Comment by filipnyquist** [comment]
@MSFTserver as requested before, could you add lets or consts instead. If you wonder why, read this nice article :) https://ponyfoo.com/articles/var-let-const Fix it and i´ll merge, looks good otherwise.

**Comment by MSFTserver** [comment]
yup I just learned how do all that properly, I'll work on redifining that stuff properly

**Comment by tzarebczan** [comment]
@MSFTserver when will you be able to get back to this? Not urgent, but PR has been sitting out there for a while now.

**Comment by tzarebczan** [comment]
Closing this for now, someone can pick this up if they feel strongly about it.

**Pull request closed without merging**
