### PR TITLE
update welcome.js

### PR DESCRIPTION
**Pull request by ykris45**
https://github.com/lbryio/lbry-wunderbot/pull/132/commits/be3052ce4c904a2572c4009f4f3b883596eb887b based minor changes from Mr Thomas , i close my PR and make new PR based Mr @tzarebczan said this for me " Chris, please keep PRs to a single item - don't change welcome text and add price commands in the same pr."

### CODE REVIEW

**Comment by ykris45** [comment]
#132

**Comment by tzarebczan** [comment]
LGTM, thanks @ykris45

**Comment by ykris45** [comment]
@filipnyquist it for welcome.js

**Comment by filipnyquist** [comment]
Merged!

**Comment by ykris45** [comment]
thanks filip and Mr @tzarebczan . You always bringing me some idea

**Pull request merged**
