### PR TITLE
Ykris45 patch 6

### PR DESCRIPTION
**Pull request by ykris45**
please Review my PR , i am will adding IDR, AUD, & CAD

### CODE REVIEW

**Comment by MSFTserver** [comment]
i cleaned up your pr a little i dont think they want so many commits as that'll get confusing 
https://github.com/lbryio/lbry-wunderbot/pull/26

**Comment by MSFTserver** [comment]
final cleanup is here https://github.com/lbryio/lbry-wunderbot/pull/29

**Comment by ykris45** [comment]
If msftserver close that. I will close

**Comment by MSFTserver** [comment]
yea gonna have to rewrite some stuff

**Pull request closed without merging**
