### PR TITLE
Add GBP to pricebot

### PR DESCRIPTION
**Pull request by aayanl**

### CODE REVIEW

**Comment by CjMapope** [comment]
CDN would be great too :D

**Comment by filipnyquist** [comment]
I´ll get back to this tomorrow as im working on refactoring the whole bot, thanks for the pull!

**Comment by lyoshenka** [comment]
@filipnyquist whats the status on this?

**Comment by filipnyquist** [comment]
@grin i would say this could be added as refactoring the bot is not my top priority

**Comment by filipnyquist** [comment]
If someone has anything else to say, feel free :)

**Pull request merged**
