### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by Coolguy3289**

### CODE REVIEW

**Comment by nikooo777** [comment]
Thank you very much for this!
To what degree did you test this? There are a few major bumps in there.

**Comment by Coolguy3289** [comment]
THAT is why I requested a review. My dev environment isn't complete for all feature testing, so I made the PR to notify you, since you're more aware of what some of the dependencies are utilized for and in what modules.. The other major bump is the bitcoin dependency. It is now deprecated and has moved to bitcoin-core. I haven't tried to implement that one yet.

**Comment by Coolguy3289** [comment]
I've also requested a dependency update from discord-irc to fix the simple-markdown issue again

**Comment by nikooo777** [comment]
hey guys, could someone please try to run this branch and see if the bot still works? I currently don't have the time to do it but I feel like this PR should be merged sooner rather than later

**Comment by Coolguy3289** [comment]
I'm working on spinning up a full dev environment. The issue is that most features typically go unused except on the LBRY server (like claimbot). So I just need to configure everything. Should have this done by the end of the week.

**Comment by kauffj** [comment]
Thanks @Coolguy3289! If we can do anything to assist env wise, please post a message in chat.

**Comment by nikooo777** [comment]
any updates on this one?

**Pull request closed without merging**
